### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by colmoneill** [jowave/vcard2to3#1]
Hi! thanks for the script, this is exactly what I was looking for!

However, when I run the script, I get an error in the remover:
```
colm@debian-co:~/git/vcard2to3$ python vcard2to3.py /home/colm/Downloads/contactsexport2.vcf 
Traceback (most recent call last):
  File "vcard2to3.py", line 152, in <module>
    main(sys.argv[1:])
  File "vcard2to3.py", line 131, in main
    remove_line = Remover(args.remove)
  File "vcard2to3.py", line 97, in __init__
    for p in patterns:
TypeError: 'NoneType' object is not iterable
```
I'm not sure how this class was supposed to work, but I don't think the script hits the loop even before this hangup. Any ideas what I'm doing wrong?

Thanks!

**Comment by jowave** [comment]
Hi, should be fixed now. 
The arguments `--remove` and `--remove-card` were not really optional.
Can you try again?
