### ISSUE TITLE
Error with QUOTED-PRINTABLE

### ISSUE THREAD

**Issue by rcarsey1** [jowave/vcard2to3#11]
This .vcf was outputted by Windows 10's "contacts.exe" program.  (Personal information obfuscated):

BEGIN:VCARD
VERSION:2.1
N:Test;Firstnamer
FN:Firstnamer Test
NOTE;ENCODING=QUOTED-PRINTABLE:1 St. Albans Brook apt 5 =0D=0A=0D=0A=0D=0AReid=92s place :=0D=0A364 3r=
d St. in Jersey City
TEL;HOME;VOICE:+15554441234
ADR;HOME:;;50 R Ave;Bergen;New Jersey;07621;United States
LABEL;HOME;ENCODING=QUOTED-PRINTABLE:50 R Ave=0D=0ABergen, New Jersey 07621=0D=0AUnited States
REV:20210608T150253Z
END:VCARD

Error output when converting:

> Traceback (most recent call last):
>   File "./1.py", line 182, in <module>
>     main(sys.argv[1:])
>   File "./1.py", line 170, in main
>     line = decoder.decode(line)
>   File "./1.py", line 65, in decode
>     decoded_line = quopri.decodestring(line).decode('UTF-8')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 41: invalid start byte
> 

Python 3.6.8 was used.

Also tried: --in_encoding ISO-8859-1

Also tried: simply copy-pasting data into a new file using the VI program.

**Comment by jowave** [comment]
There was an error in the decoding of quoted printable strings. They were always decoded as utf-8, which may fail, if the original encoding was different. I am now using the ` --in_ecoding` parameter to decode quoted printable text. (The encoding of the generated output file is independent of that.)

For your example, I think you need to use `--in_encoding Windows-1252`.
