### ISSUE TITLE
`FN` field is optional in the vcard 2.1 spec.

### ISSUE THREAD

**Issue by jmon12** [jowave/vcard2to3#12]
## Description

An imported vcard with a `N` field but no `FN` field is treated as an invalid card and is therefore not written. This is against the specification of the vcard 2.1 standard, see [wikipedia](https://en.wikipedia.org/wiki/VCard) and in particular the following. 
Note that at least for my old Nokia phone, only the `N` field is present.

| Field | vCard 2.1 | vCard 3 | vCard 4 |
| ------ | ------------- | ----------- | ---------- |
| `N` | Required | Required | Optional |
| `FN` | **Optional** | Required | Required |

Let me know if I misunderstood something. I only googled for the standards and didn't double check Wikipedia's info.

## Solution

An easy fix would be to treat the `N` field in the same way you do with the `NICKNAME` field, but without removing the field. Note that this would make a vcard3 valid even though it only has a `N` field and no `FN` field (which violates the standard). What do you think? I will propose you a MR soon.

PS: thanks a lot for the great work, saving me for transferring my old Nokia's contacts.

**Comment by jmon12** [comment]
It might be related with the issue #8 since the symptom is an empty output file.

**Comment by jowave** [comment]
Hi, thanks for your input and the MR #13, I will look into it. (Hopefully I will find time at the weekend.)

**Comment by jmon12** [comment]
My pleasure to contribute! No hurry. I will be using your scripts a bit during the following days and therefore maybe proposing some improvements as well.
Let me know if anything is unclear.
Have a good night!
