### ISSUE TITLE
UTF8 Encoded Nickname isn't detected

### ISSUE THREAD

**Issue by Bip901** [jowave/vcard2to3#16]
**Describe the bug**
`X-ANDROID-CUSTOM:vnd.android.cursor.item/nickname` is not detected properly if `CHARSET=UTF-8` is present, which is the case when exporting from my Android 13 Samsung device.

**To Reproduce**
1. Prepare input files '[utf8-nickname-test.txt](https://github.com/jowave/vcard2to3/files/11198292/utf8-nickname-test.txt)' (extension .txt because GitHub doesn't allow .vcf uploads)
3. Run script 'vcard2to3.py'
4. Observe that the property is not replaced with `NICKNAME`.
5. Expected result: [utf8-nickname-test-expected.txt](https://github.com/jowave/vcard2to3/files/11198308/utf8-nickname-test-expected.txt)

**Additional context**
I've already implemented a solution and I'd like to get permission to push it to a separate branch.
Alternatively, feel free to make the changes yourself in `vcard2to3.py` line 152:

`'^X-ANDROID-CUSTOM(;CHARSET=UTF-8)?:vnd.android.cursor.item/nickname;([^;]+);.*'), 'NICKNAME\\1:\\2'))`

This allows an optional `CHARSET=UTF-8` field, and persists it after conversion.

**Comment by jowave** [comment]
Thanks for your suggestion.
I have added it, but changed it to not persist the ` CHARSET=UTF-8` parameter, because the vCard 3.0 does not support charset parameters ([in section 5](https://www.rfc-editor.org/rfc/rfc2426#section-5)).

**Comment by Bip901** [comment]
Awesome, cheers! 🍻

**Comment by Bip901** [comment]
Note that `CHARSET=UTF-8` **is** persisted in the N and FN fields - you might want to remove those, too.

**Comment by jowave** [comment]
Yeah, would be more conforming to vCard 3.0.
