### ISSUE TITLE
Quoted printable line breaks handling

### ISSUE THREAD

**Issue by Disassembler0** [jowave/vcard2to3#3]
Hi,

I'm in the same predicament as you were and I have a VCF in VCARD 2.1 format exported from Android 4.x which I'm trying to import to NextCloud. The extra part in my case is that some records are in cyrilic, so the `N` and `FN` fileds are encoded via quoted printable and are split to multiple lines, where each chunk is 70 characters long. This is given by RFC 2045, paragraph 6.7.5, but the script doesn't seem to reflect this and fails on line with the first chunk with 

```
Traceback (most recent call last):
  File "./vcard2to3.py", line 154, in <module>
    main(sys.argv[1:])
  File "./vcard2to3.py", line 142, in main
    line = decode(line)
  File "./vcard2to3.py", line 55, in __call__
    return self.decode(line)
  File "./vcard2to3.py", line 62, in decode
    line = quopri.decodestring(line).decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 25: unexpected end of data
```

As per RFC 2045, every *softly broken* line ends with `=` sign. Some examples:

```
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;=D0=86=D0=B3=D0=BE=D1=80=20=D0=97=D0=B0=D0=B3=D0=BE=D1=80=D1=81=D0=BA=
=D1=96;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=D0=86=D0=B3=D0=BE=D1=80=20=D0=97=D0=B0=D0=B3=D0=BE=D1=80=D1=81=D0=BA=
=D1=96
```

```
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;=D0=90=D0=BB=D0=B5=D1=88=20=D0=9C=D0=B0=D0=BB=D0=B0=D1=88=D0=B5=D0=BA=
;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=D0=90=D0=BB=D0=B5=D1=88=20=D0=9C=D0=B0=D0=BB=D0=B0=D1=88=D0=B5=D0=BA=

```
(the last blank line in the second example is a part of the `FN`).

The quick and dirty solution for this (which I have used) would be to preprocess the script with multiline regex-replace and join the lines while removing the trailing `=`. Something in terms of 

```
import re

with open('file.vcf') as f:
    text = f.read()


s = re.compile(r'=\n(.*)', re.MULTILINE)
text = re.sub(s,  r'\1', text)
```

I haven't given it much thought, though, so there may be some other much more elegant solution.

**Comment by jowave** [comment]
I have improved the handling of multi-line quoted printable content. It is not terrible robust, but it should do the trick.

@Disassembler0 can you check, if this works for you?

**Comment by Disassembler0** [comment]
Works like a charm. Awesome. Thank you.
