### ISSUE TITLE
Invalid vcard if decoding quoted printable results in embedded newlines

### ISSUE THREAD

**Issue by mozjag** [jowave/vcard2to3#4]
I ran into a problem with some converted cards where the notes consisted of multiple lines. The problem is that the embedded newlines, after being converted, weren't encoded, so the card looked something like:

```
NOTE:bla bla
bla bla bla
bla bla
```

when it should've looked like:

```
NOTE:bla bla\nbla bla bla\nbla bla
```

See https://tools.ietf.org/html/rfc6350#section-3.4

**Comment by mozjag** [comment]
BEGIN:VCARD
VERSION:2.1
TITLE:XXXXXXXXXXXXX
FN:XXXXXXXXXX
N:XXXXXXXXXX;;;;
TEL;VOICE:+31 00 0000000
ADR;WORK:;;XXXXXXXXXX;XXXXXXXXXX;;;
NOTE;ENCODING=QUOTED-PRINTABLE;CHARSET=utf-8:XXXXXXXXXX =E2=82=
=AC ##,##=0D=0AXXXXXXXXXX =E2=82=AC ##,##=0D=0A
END:VCARD

Expected conversion for the NOTE line:

NOTE:XXXXXXXXXX € ##,##\nXXXXXXXXXX € ##,##\n

**Comment by jowave** [comment]
@mozjag I have added newline escaping, if they come from quoted printable.
