### ISSUE TITLE
Support flipped CHARSET and QUOTED-PRINTABLE

### ISSUE THREAD

**Issue by mozjag** [jowave/vcard2to3#5]
Quick hack I needed to convert my v2.1 cards (thanks for this tool btw!):

```
    quoted = re.compile('.*(;ENCODING=QUOTED-PRINTABLE;CHARSET=.+?):')
````

Note the non-greedy match and the colon at the end.

**Comment by jowave** [comment]
Hi, I won't be able to look into this until the end of the month. Can you add a complete example vcard in the meantime.

**Comment by mozjag** [comment]
BEGIN:VCARD
VERSION:2.1
TITLE:XXXXXXXXXXXXX
FN:XXXXXXXXXX
N:XXXXXXXXXX;;;;
TEL;VOICE:+31 00 0000000
ADR;WORK:;;XXXXXXXXXX;XXXXXXXXXX;;;
NOTE;ENCODING=QUOTED-PRINTABLE;CHARSET=utf-8:XXXXXXXXXX =E2=82=
=AC ##,##=0D=0AXXXXXXXXXX =E2=82=AC ##,##=0D=0A
END:VCARD

So basically instead of the CHARSET bit being followed by the ENCODING bit, it's the other way around. Shouldn't be too difficult to adjust the regex to handle both cases.

Note also the embedded newline (=0D=0A) triggering the other open issue (#4 ) . I'll copy-paste this example there as well.

**Comment by jowave** [comment]
I took me a bit longer ;-), but CHARSET is now optional and can precede or follow the 'ENCODING=QUOTED-PRINTABLE'.
